### ISSUE TITLE
Wrapper taking up full page height.

### ISSUE THREAD

**Issue by singhpratyush** [iiitv/college_website#23]

**Comment by singhpratyush** [comment]
Probably due to `max-height: 100vh` in `style.css` - 

``` css
.wrapper{
    max-height: 100vh;
    display: flex;
    flex-direction: column;
}
```
